name: Publish

on:
  push:
    branches:
      - master
    paths:
      - "**.py"
      - ".github/workflows/publish.yaml"
      - "pyproject.toml"
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: "1.6.0"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Check package versions
        run: |
          echo "PYPI_VERSION=$(poetry search mkdocs-onecompiler-plugin|grep '^mkdocs-onecompiler-plugin'|grep -o '[0-9]\+[.][0-9]\+[.][0-9]\+')" >> $GITHUB_ENV;
          echo "CURRENT_VERSION=$(poetry version -s)" >> $GITHUB_ENV;
      - name: Publish
        if: ${{ env.CURRENT_VERSION != env.PYPI_VERSION }}
        run: |
          echo "${{ env.CURRENT_VERSION }} != ${{ env.PYPI_VERSION }}";
          poetry build && poetry publish -u __token__ -p "${{ secrets.PYPI_TOKEN }}";
